remove init container

diff --git a/deploy/all-in-one.yaml b/deploy/all-in-one.yaml
--- a/deploy/all-in-one.yaml
+++ b/deploy/all-in-one.yaml
@@ -556,29 +556,29 @@ spec:
         runAsGroup: 1000
         runAsNonRoot: true
         runAsUser: 1000
-      initContainers:
-        - command:
-            - /bin/sh
-            - -exc
-            - |
-              echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-              if test $STATUSCODE -ne 200; then
-                  echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-                  exit 1
-              fi
-          name: frontend-check
-          securityContext:
-            allowPrivilegeEscalation: false
-            capabilities:
-              drop:
-                - all
-            privileged: false
-            readOnlyRootFilesystem: true
-          image: busybox:latest
-          env:
-            - name: FRONTEND_ADDR
-              value: "frontend:80"
+      # initContainers:
+      #   - command:
+      #       - /bin/sh
+      #       - -exc
+      #       - |
+      #         echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+      #         STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+      #         if test $STATUSCODE -ne 200; then
+      #             echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+      #             exit 1
+      #         fi
+      #     name: frontend-check
+      #     securityContext:
+      #       allowPrivilegeEscalation: false
+      #       capabilities:
+      #         drop:
+      #           - all
+      #       privileged: false
+      #       readOnlyRootFilesystem: true
+      #     image: busybox:latest
+      #     env:
+      #       - name: FRONTEND_ADDR
+      #         value: "frontend:80"
       containers:
         - name: main
           securityContext:
